### ISSUE TITLE
Can't parse arbitrarily named layers

### ISSUE THREAD

**Issue by nickcoutsos** [bmcgavin/zmk-parser#2]
I tried parsing a keymap that seems to compile fine, but it seems that as long as the layer name doesn't have the suffix `_layer` the parser will fail with

```
Parse error, expected brace at char 5 {...}
```

followed by the keymap content. I haven't seen documentation that suggests any layer naming requirements, and it looks like there are examples in the zmk repository that don't follow this pattern.

**Comment by bmcgavin** [comment]
Hello again! I fixed this in a branch but have not been keeping up best possible development standards on this project - it's now hopefully fixed in main.

The DTSI parser is an issue in itself, who would have thought that a parsing logic based entirely on regular expressions would be flaky? :thinking:
